@startuml
class Class01 {
  String data
  void methods()
}
class Class03 {
  String data
  void methods()
}
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10
@enduml